- name: Create EC2 instance using AWS CLI
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Launch EC2 instance
    shell: |
      aws ec2 run-instances --image-id ami-0f9d9a251c1a44858 --count 1 --instance-type t2.micro --key-name ansible-demo  --subnet-id subnet-0cd9461882dfdb31d
    register: ec2_instance
